name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: '6.x'
    - run: nuget restore Wincent.sln

    - name: Build Release
      run: |
        msbuild Wincent.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin\Release

    - name: Get version from tag
      if: startsWith(github.ref, 'refs/tags/')
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Get version from changelog
      if: github.event_name == 'workflow_dispatch'
      id: get_changelog_version
      run: |
        $version = (Get-Content CHANGELOG.md | Select-String -Pattern '## \[(.*?)\]' | Select-Object -First 1).Matches.Groups[1].Value
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Pack NuGet package
      run: |
        cd Wincent
        nuget pack -Properties Configuration=Release

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        $package = Get-ChildItem -Path "Wincent" -Filter "*.nupkg" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        nuget push $package.FullName $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
